FROM oven/bun:1.1.20-debian

ENV TZ Asia/Tokyo

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

# uid=1000
USER bun

CMD ["sh"]
